[package]
name = "aws_nvim"
version = "0.1.0"
edition = "2024"

[dependencies]
nvim-oxi = "0.4"
aws-config = "1"
aws-sdk-glue = "1"
tokio = { version = "1", features = ["full"] }

[lib]
crate-type = ["cdylib"]
